from sqlalchemy import Column, Integer, Text, DateTime, ForeignKey, JSON
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from app.db.database import Base


class SessionReview(Base):
    """
    Session review generated by ClerkAgent after session ends.

    Stores session summary and key events extracted from conversation.
    Only created for closed sessions.
    """
    __tablename__ = "session_reviews"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    message_review = Column(Text, nullable=False)  # Session summary text
    key_events = Column(JSON, default=list)        # List of key events
    created_at = Column(DateTime, server_default=func.now(), nullable=False)

    session = relationship("Session", back_populates="review", uselist=False)
