"""add_session_timing_fields

Revision ID: 0103296fc90c
Revises: a289f2750b88
Create Date: 2025-12-11 11:29:57.395093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0103296fc90c'
down_revision = 'a289f2750b88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_items_id'), table_name='user_profile_items')
    op.drop_index(op.f('ix_user_profile_items_user_id'), table_name='user_profile_items')
    op.drop_table('user_profile_items')
    op.add_column('sessions', sa.Column('active_duration_seconds', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sessions', sa.Column('turn_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sessions', sa.Column('overtime_reminder_count', sa.Integer(), nullable=False, server_default='0'))
    op.drop_constraint(op.f('user_contexts_user_id_key'), 'user_contexts', type_='unique')
    op.drop_index(op.f('ix_user_contexts_user_id'), table_name='user_contexts')
    op.create_index(op.f('ix_user_contexts_user_id'), 'user_contexts', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_contexts_id'), 'user_contexts', ['id'], unique=False)
    op.drop_index(op.f('ix_user_onboardings_user_question'), table_name='user_onboardings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_onboardings_user_question'), 'user_onboardings', ['user_id', 'question_number'], unique=False)
    op.drop_index(op.f('ix_user_contexts_id'), table_name='user_contexts')
    op.drop_index(op.f('ix_user_contexts_user_id'), table_name='user_contexts')
    op.create_index(op.f('ix_user_contexts_user_id'), 'user_contexts', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_contexts_user_id_key'), 'user_contexts', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('sessions', 'overtime_reminder_count')
    op.drop_column('sessions', 'turn_count')
    op.drop_column('sessions', 'active_duration_seconds')
    op.create_table('user_profile_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence', postgresql.ENUM('low', 'medium', 'high', name='confidencelevel'), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('onboarding', 'clerk', name='profilesource'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_profile_items_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profile_items_pkey'))
    )
    op.create_index(op.f('ix_user_profile_items_user_id'), 'user_profile_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_profile_items_id'), 'user_profile_items', ['id'], unique=False)
    # ### end Alembic commands ###
