"""add_review_and_key_events_to_sessions

Revision ID: a3df599320a6
Revises: 9bd1a3def5f3
Create Date: 2025-12-06 14:22:34.083949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3df599320a6'
down_revision = '9bd1a3def5f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_session_messages_id'), 'session_messages', ['id'], unique=False)
    op.add_column('sessions', sa.Column('review_text', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('key_events', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'key_events')
    op.drop_column('sessions', 'review_text')
    op.drop_index(op.f('ix_session_messages_id'), table_name='session_messages')
    # ### end Alembic commands ###
